# Site settings
title: Asia Foundation
email: nicholas.doiron@asiafoundation.org
description: Asia Foundation's Digital Media and Technology programs
baseurl: ""
url: "http://asiafoundation.github.io"

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line: 465 California St, San Francisco, CA 94104
  - line:
  # Feel free to add more lines here
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
